
language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-25
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-25
  - extra-android-m2repository